# Generated by Django 3.0 on 2019-12-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_auto_20191205_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='escolaridade_minima',
            field=models.CharField(choices=[('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio'), ('TC', 'Tecnólogo'), ('ES', 'Ensino Superior'), ('PM', 'Pós / MBA / Mestrado'), ('DR', 'Doutorado')], default='EF', max_length=2),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='nome',
            field=models.CharField(max_length=128),
        ),
    ]
