# Generated by Django 3.0 on 2019-12-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=256)),
                ('senha', models.CharField(max_length=32)),
                ('pretensao_salarial', models.IntegerField(choices=[(1, 'ate 1.000'), (2, 'de 1.000 a 2.000'), (3, 'de 2.000 a 3.000'), (4, 'acima de 3.000')], default=1)),
                ('experiencia', models.TextField(null=True)),
                ('nivel_escolaridade', models.CharField(choices=[('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio'), ('TC', 'Tecnólogo'), ('ES', 'Ensino Superior'), ('PM', 'Pós / MBA / Mestrado'), ('DR', 'Doutorado')], default='EF', max_length=2)),
            ],
        ),
    ]
